source 'https://rubygems.org'
gem 'rails', '3.2.15'
gem 'pg'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
gem 'unicorn'
gem 'capistrano', '2.11.2'
gem 'activerecord-postgres-hstore'
gem 'browser'
gem 'quiet_assets'
gem 'thin'
gem 'will_paginate'
