# coding: utf-8
class ProgramController < ApplicationController
  def index
    if params[:j] == "19"
      @content = "<h2>19 Mars : <span>Management de proximité et santé au travail</span></h2><ul><li>9 h&nbsp;: Accueil par Max Ponseillé, Président de la Fondation&nbsp;<br/><br/></li><li>9h 15&nbsp;: Introduction : Jean Auroux, ancien Ministre du travail&nbsp;<br/><br/></li><li>10h&nbsp;: La chaîne du commandement. M Bel, DRH adjoint, Groupe SNI (société Nationale Immobilière)&nbsp; &nbsp;<br/><br/></li><li>10h 30&nbsp;: Le management&nbsp;: applications en entreprise et dans le milieu sportif. Un représentant d’une entreprise et Olivier Maurelli, ancien international de Handball, préparateur sportif&nbsp;<br/><br/></li><li>11h&nbsp;: Pause&nbsp;<br/><br/></li><li>11h 15&nbsp;: Hommes et femmes, y a-t-il des différences dans le style de management&nbsp;? Noëlle Sailly, Club des Femmes chefs d’entreprise&nbsp;<br/><br/></li><li>11h 35&nbsp;: Table ronde. Invités&nbsp;: partenaires sociaux (Alain Alphon Layre, CGT – un représentant d’une organisation patronale), ARACT, Florence Palpacuer, Professeur à l’Université Montpellier 1, responsable du M2 management des organisations et du développement responsable&nbsp;<br/><br/></li><li>12h 30&nbsp;: Déjeuner – buffet&nbsp;<br/><br/></li><li>14h&nbsp;: Approche médicale. Les effets du stress sur la santé. Comment identifier ces effets, avec quels marqueurs&nbsp;? Les aspects d'évaluation des flux sanguins cérébraux et du niveau&nbsp;d'oxygénation&nbsp;comme&nbsp;témoins&nbsp;d'activation&nbsp;et&nbsp;de&nbsp;santé&nbsp;: professeur Stéphane Perrey – Les marqueurs neurologiques&nbsp;: professeur Karen Ritchie. Les Marqueurs sensorimoteurs&nbsp;: professeur Benoit Bardy&nbsp;<br/><br/></li><li>14h 45&nbsp;: Synthèse de l’approche médicale&nbsp;: Docteur Marie-Laure Hemery, Ametra&nbsp;<br/><br/></li><li>15h&nbsp;: Bonnes pratiques de management&nbsp;: Docteur Marie-Laure Hemery, à partir d’une étude québécoise &nbsp;<br/><br/></li><li>15h 15&nbsp;: Le coût juridique d’un mauvais management. Cédric Riot, avocat spécialiste du droit du travail &nbsp;<br/><br/></li><li>15h 45&nbsp;: Le coût économique d’un mauvais management vs le retour sur investissement d’un bon management. Interventions de l’OPPBTP (expérience DIMECO) et de Florence Noguera, Professeur des Universités, Université Montpellier 3 &nbsp;<br/><br/></li><li>16h 15&nbsp;: Table ronde. Quelles réponses apporter&nbsp;? Représentants des partenaires sociaux (ORST), de la DIRECCTE, la CARSAT, de l’Apave, un médecin du travail&nbsp;<br/><br/></li><li>17 h&nbsp;: conclusion par Jean Auroux&nbsp;<br/><br/></li></ul><p>Animation Yves Jolis</p>"
    elsif params[:j] == "20"
      @content = "<h2> 20 Mars : <span>Festival du film la santé au travail</span> </h2> <ul> <li>8h 30&nbsp;: Accueil&nbsp;<br/><br/></li><li>9h&nbsp;: Introduction par Jean Auroux&nbsp;<br/><br/></li><li>9h 15&nbsp;: Témoignage des lauréats de l’année précédente (Dalkia/MSA) &nbsp;<br/><br/></li><li>De 9h30 à 11 h&nbsp;: projections&nbsp;<br/><br/></li><li>11h&nbsp;: Pause&nbsp;<br/><br/></li><li>11h 15&nbsp;: Table ronde sur le thème «&nbsp;le film, outil de prévention&nbsp;». Invités&nbsp;: un représentant du MASE (Manuel d’Amélioration Sécurité des Entreprises – à confirmer), un représentant de l’INRS (à confirmer), Marc Galabru, homme de lettres et de théâtre.&nbsp;<br/><br/></li><li>11h 45&nbsp;: Reprise des projections&nbsp;<br/><br/></li><li>12h 45&nbsp;: Vote du public/ déjeuner- buffet/ délibération du jury&nbsp;<br/><br/></li><li>14h 15&nbsp;: Projection de films dans le cadre du prix «&nbsp;jeunes réalisateurs&nbsp;»&nbsp;<br/><br/></li><li>15h 15&nbsp;: Pause et délibération du jury&nbsp;<br/><br/></li><li>15h 30&nbsp;: Intervention de Marc Galabru &nbsp;<br/><br/></li><li>16h&nbsp;: Remise des prix (prix du public et prix du jury pour les films d’entreprise, prix «&nbsp;jeunes réalisateurs&nbsp;», prix TPE du bâtiment décerné par la CAPEB LR)&nbsp;<br/><br/></li><li>16h 30&nbsp;: Conclusion par Jean Auroux&nbsp;<br/><br/></li> </ul> <p>Animation Yves Jolis</p>"
    else
      redirect_to root_url
    end
  end
end
